octopus:
  environments:
    - development
    - production
  development:
    shards:
      base_remota_1:
        adapter: postgresql
        encoding: unicode
        database: ponto
        pool: 5
        username: postgres
        password: Maker@1
        host: 192.168.1.2
        port: 5432
  production:
    shards:
      base_remota_1:
        adapter: postgresql
        encoding: unicode
        database: ponto
        pool: 5
        username: postgres
        password: Maker@1
        host: 192.168.1.2
        port: 5432

  