require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OfficeHoursController do

  # This should return the minimal set of attributes required to create a valid
  # OfficeHour. As you add validations to OfficeHour, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OfficeHoursController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all office_hours as @office_hours" do
      office_hour = OfficeHour.create! valid_attributes
      get :index, {}, valid_session
      assigns(:office_hours).should eq([office_hour])
    end
  end

  describe "GET show" do
    it "assigns the requested office_hour as @office_hour" do
      office_hour = OfficeHour.create! valid_attributes
      get :show, {:id => office_hour.to_param}, valid_session
      assigns(:office_hour).should eq(office_hour)
    end
  end

  describe "GET new" do
    it "assigns a new office_hour as @office_hour" do
      get :new, {}, valid_session
      assigns(:office_hour).should be_a_new(OfficeHour)
    end
  end

  describe "GET edit" do
    it "assigns the requested office_hour as @office_hour" do
      office_hour = OfficeHour.create! valid_attributes
      get :edit, {:id => office_hour.to_param}, valid_session
      assigns(:office_hour).should eq(office_hour)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OfficeHour" do
        expect {
          post :create, {:office_hour => valid_attributes}, valid_session
        }.to change(OfficeHour, :count).by(1)
      end

      it "assigns a newly created office_hour as @office_hour" do
        post :create, {:office_hour => valid_attributes}, valid_session
        assigns(:office_hour).should be_a(OfficeHour)
        assigns(:office_hour).should be_persisted
      end

      it "redirects to the created office_hour" do
        post :create, {:office_hour => valid_attributes}, valid_session
        response.should redirect_to(OfficeHour.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved office_hour as @office_hour" do
        # Trigger the behavior that occurs when invalid params are submitted
        OfficeHour.any_instance.stub(:save).and_return(false)
        post :create, {:office_hour => {}}, valid_session
        assigns(:office_hour).should be_a_new(OfficeHour)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OfficeHour.any_instance.stub(:save).and_return(false)
        post :create, {:office_hour => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested office_hour" do
        office_hour = OfficeHour.create! valid_attributes
        # Assuming there are no other office_hours in the database, this
        # specifies that the OfficeHour created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OfficeHour.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => office_hour.to_param, :office_hour => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested office_hour as @office_hour" do
        office_hour = OfficeHour.create! valid_attributes
        put :update, {:id => office_hour.to_param, :office_hour => valid_attributes}, valid_session
        assigns(:office_hour).should eq(office_hour)
      end

      it "redirects to the office_hour" do
        office_hour = OfficeHour.create! valid_attributes
        put :update, {:id => office_hour.to_param, :office_hour => valid_attributes}, valid_session
        response.should redirect_to(office_hour)
      end
    end

    describe "with invalid params" do
      it "assigns the office_hour as @office_hour" do
        office_hour = OfficeHour.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OfficeHour.any_instance.stub(:save).and_return(false)
        put :update, {:id => office_hour.to_param, :office_hour => {}}, valid_session
        assigns(:office_hour).should eq(office_hour)
      end

      it "re-renders the 'edit' template" do
        office_hour = OfficeHour.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OfficeHour.any_instance.stub(:save).and_return(false)
        put :update, {:id => office_hour.to_param, :office_hour => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested office_hour" do
      office_hour = OfficeHour.create! valid_attributes
      expect {
        delete :destroy, {:id => office_hour.to_param}, valid_session
      }.to change(OfficeHour, :count).by(-1)
    end

    it "redirects to the office_hours list" do
      office_hour = OfficeHour.create! valid_attributes
      delete :destroy, {:id => office_hour.to_param}, valid_session
      response.should redirect_to(office_hours_url)
    end
  end

end
